name: Expo Build and Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Use Node.js '12.x'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        
      - name: Expo GitHub Action
        uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          
      - name: Install dependencies
        run: yarn 
        
      - name: Build apk  
        run: expo publish
